require:
  - standard
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml # use the standardrb config file as the base

AllCops:
  NewCops: enable
  Exclude: # ignore files in these directories when running the linter
    - node_modules/**/*
    - public/**/*
    - vendor/**/*

Rails:
  Enabled: true # enable rubocop-rails
RSpec:
  Enabled: true # enable rubocop-rspec
RSpec/DescribeClass:
  Enabled: false # ignore missing comments on classes
Rails/FilePath:
  EnforcedStyle: arguments
