# .github/workflows/ci.yml

name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.3
          bundler-cache: true
      - name: YARN
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --silent
      - name: Unit tests
        run: bundle exec rails spec
